[[rewrites]]
source = "/payment/approve"
destination = "/api/payment-approve"

[[rewrites]]
source = "/payment/complete"
destination = "/api/payment-complete"

[[rewrites]]
source = "/payment/cancel"
destination = "/api/payment-cancel"
