[[redirects]]
source = "/payment/approve"
destination = "/api/payment-approve"
statusCode = 200

[[redirects]]
source = "/payment/complete"
destination = "/api/payment-complete"
statusCode = 200

[[redirects]]
source = "/payment/cancel"
destination = "/api/payment-cancel"
statusCode = 200
